import type { AppProps } from 'next/app';
import { ReactElement, ReactNode, Suspense, useRef, useEffect, useState } from 'react';
import DefaultLayout from '../components/Layouts/DefaultLayout';
import { Provider } from 'react-redux';
import { useNetworkState } from 'react-use';
import store from '../store/index';
import Head from 'next/head';

import { appWithI18Next } from 'ni18n';
import { ni18nConfig } from '../ni18n.config.ts';

// Perfect Scrollbar
import 'react-perfect-scrollbar/dist/css/styles.css';

import '../styles/tailwind.css';
import { NextPage } from 'next';

export type NextPageWithLayout<P = {}, IP = P> = NextPage<P, IP> & {
    getLayout?: (page: ReactElement) => ReactNode;
}

type AppPropsWithLayout = AppProps & {
    Component: NextPageWithLayout;
}

const App = ({ Component, pageProps }: AppPropsWithLayout) => {
    const getLayout = Component.getLayout ?? ((page) => <DefaultLayout>{page}</DefaultLayout>);
    const state = useNetworkState();
    const isOnline = useRef(true);

    useEffect(() => {
        if (isOnline.current && !state.online) {
            isOnline.current = false;
            // notify.error('Mất kết nối mạng');
        }
        if (!isOnline.current && state.online) {
            isOnline.current = true;
            // notify.success('Đã có kết nối mạng');
        }
    }, [state]);

    return (
        <Provider store={store}>
            <Head>
                {/* <title>Vangtat</title> */}
                <meta charSet="UTF-8" />
                <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" type="image/ico" href="%PUBLIC_URL%/favicon.ico" />
            </Head>
            {getLayout(<Component {...pageProps} />)}
        </Provider>
    );
};
export default appWithI18Next(App, ni18nConfig);
